Lesson 3
Akamka/robot-dreams-courses pull request #2
Opened 2022-12-07 16:58 UTC by Akamka

2022-12-07 21:22 UTC, klymenok requested changes
There are a few mistakes, fit them, please

2022-12-07 21:22 UTC, klymenok commented on homework_3/homework3.py
> +age_in_years = 17
This value should be calculated based on `age_in_month` value

2022-12-07 21:22 UTC, klymenok commented on homework_3/homework3.py
> +my_age = "Му name is Dmytro and I’m 17 years old"
Here you should use string concatenation to put `17` not as a raw value but as a value from the variable `age_in_years`. You can user simple concatenation ("some" + "thing" + some_variable), or f-strings

2022-12-07 21:22 UTC, klymenok commented on homework_3/homework3.py
> +d=(2*5+6)**2
The final value should be a string. To create a string from integers you can transform integers to strings using str() function and concatenate them using `+` sign

2022-12-07 21:22 UTC, klymenok commented on lesson_3.py
> +#1
This file is duplicated. Remove it, please

2022-12-11 11:49 UTC, Akamka commented on homework_3/homework3.py
> +age_in_years = 17
І redid this work. Іs everything ok now?

2022-12-11 19:27 UTC, klymenok commented on homework_3/homework3.py
> +age_in_years = 17
To calculate this do not use raw value. You can use a value stored in `age_in_month`, like this:
`age_in_years  = int(age_in_month / 12)`

2022-12-14 14:50 UTC, merged